/*
 * Copyright 2025 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
import { contains, indexResource } from '@adobe/helix-shared-indexer';
import { isSiteConfig } from './utils.js';

/**
 * Index a single page for a single index.
 *
 * @param {string} path page path
 * @param {import('@adobe/helix-shared-indexer').Index} config a single index configuration
 * @param {object} page headers and body, if HTML
 * @param {boolean} autoGenerated true if the index is autogenerated
 * @param {object} log logger
 * @returns object with either message, noIndex or record
 */
export function indexPage(path, config, page, autoGenerated, log) {
  if (!contains(config, path)) {
    return {
      message: 'requested path does not match index configuration',
    };
  }
  if (page.gone) {
    return {
      noIndex: true,
      message: 'requested path returned a 301 or 404',
    };
  }
  if (!isSiteConfig(config) && !page.body) {
    return {
      message: 'non-HTML pages can only be added to site configurations',
    };
  }

  const internal = autoGenerated || config.name === '#simple';
  let configToPass = config;
  let checkRobots = false;

  if (internal && page.body && !config.properties.find(({ name }) => name === 'robots')) {
    configToPass = {
      properties: [
        ...config.properties,
        {
          name: 'robots',
          select: 'head > meta[name="robots"]',
          value: 'attribute(el, "content")',
        },
      ],
    };
    checkRobots = true;
  }

  const record = indexResource(path, page, configToPass, log);
  if (checkRobots) {
    if (record.robots.toLowerCase().includes('noindex')) {
      log.info(`[index] indexed resource specified 'noindex' in robots: not added to ${config.name}`);
      return {
        noIndex: true,
        message: 'requested path has \'noindex\' property set',
      };
    }
    if (internal) {
      delete record.robots;
    }
  }
  return { record };
}
