/*
 * Copyright 2025 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
import util from 'util';
import { contains } from '@adobe/helix-shared-indexer';
import processQueue from '@adobe/helix-shared-process-queue';
import { HelixStorage } from '@adobe/helix-shared-storage';
import { Job } from '../job/job.js';
import { fetchPage } from './fetch-page.js';
import { indexPageInIndex } from './index-page.js';
import { IndexContents } from './IndexContents.js';
import { IndexMap } from './IndexMap.js';
import { IndexMessages } from './IndexMessages.js';
import { PrefixOrPathList } from './PrefixOrPathList.js';
import {
  containsPath, fetchExtendedIndex, shouldIndex,
  getIndexType, hasSiteConfig,
  getIndexTargets, getFetchHeaders,
} from './utils.js';
import { installSimpleSitemap } from '../sitemap/utils.js';
import { splitExtension, toResourcePath, toWebPath } from '../support/RequestInfo.js';

/**
 * Concurrency to use when indexing pages.
 */
const JOB_CONCURRENCY = 20;

/**
 * Maximum number of paths to reindex.
 */
const MAXIMUM_NUM_PATHS = 50000;

/**
 * @typedef BulkContext
 * @property {import('@adobe/helix-shared-indexer').IndexConfig} index index configuration
 * @property {boolean} autoGenerated whether the index is auto-generated
 * @property {boolean} includeOther whether to include other indexes
 * @property {Array<string>} excludes excludes to ignore
 * @property {IndexMessages} messages messages to send with the queue client
 * @property {object} headers headers to pass when fetching
 * @property {HelixStorage} storage storage to use
 * @property {string} type backend type
 */

/**
 * Index job class.
 */
export class IndexJob extends Job {
  /** @type {string} */
  indexNames;

  /** @type {boolean} */
  isFullReindex;

  /** @type {PrefixOrPathList} */
  pathList;

  /**
   * Initialize the job.
   * @return {Promise<void>}
   */
  async initialize(data) {
    this.indexNames = data.indexNames;

    const { paths: prefixesOrPaths } = data;
    this.pathList = new PrefixOrPathList(prefixesOrPaths);

    const { prefixes, paths } = this.pathList;
    this.isFullReindex = this.indexNames.length === 0
      && util.isDeepStrictEqual(prefixes, ['/']) && paths.length === 0;
  }

  get context() {
    return this.ctx;
  }

  /**
   * Whether to include index in bulk-reindex.
   *
   * @param {string} name index name
   * @return true to include, false to exclude
   */
  includeIndex(name) {
    const { indexNames } = this;
    return indexNames.length === 0 || indexNames.includes(name);
  }

  /**
   * Prepare the bulk context.
   *
   * @returns {Promise<BulkContext>} bulk context
   */
  async prepare() {
    const { context, info } = this;
    const { config } = context;
    const { org, site } = info;

    const index = await fetchExtendedIndex(context, info);
    const autoGenerated = index['auto-generated'] === true;
    const includeOther = hasSiteConfig(index);
    const excludes = getIndexTargets(index);
    const messages = new IndexMessages(org, site);
    const headers = await getFetchHeaders(context, info);
    const storage = HelixStorage.fromContext(context).contentBus();

    return {
      index,
      autoGenerated,
      includeOther,
      excludes,
      headers,
      messages,
      storage,
      type: config.content.source.type,
    };
  }

  /**
   * Collect all pages that are live in storage and return their resource paths.
   *
   * @param {Array<import('../support/utils.js').PrefixOrPath>} paths paths to index
   * @param {HelixStorage} storage storage to use
   * @returns {Promise<Array<string>>} live paths
   */
  async collectPaths(storage) {
    const { context, pathList: { prefixes, paths } } = this;
    const { contentBusId } = context;

    const resourcePaths = [];
    await processQueue([...prefixes], async (prefix) => {
      const entries = await storage.list(`${contentBusId}/live${prefix}`);
      if (entries.length > MAXIMUM_NUM_PATHS) {
        throw new Error(`Too many paths with prefix '${prefix}': ${entries.length}, maximum allowed is: ${MAXIMUM_NUM_PATHS}`);
      }
      resourcePaths.push(...entries.map(({ key }) => key.substring(contentBusId.length + 5)));
    });
    paths.forEach((webPath) => {
      resourcePaths.push(toResourcePath(webPath));
    });
    return resourcePaths;
  }

  /**
   * Returns the map of pages to index along with the hashes of the already indexed content.
   *
   * @param {BulkContext} bulkContext bulk context
   * @returns {Promise<IndexMap>} map of paths to reindex
   */
  async getIndexData(bulkContext) {
    const { context, pathList } = this;
    const { contentBusId, log } = context;
    const {
      storage, index, includeOther, excludes,
    } = bulkContext;

    const resourcePaths = await this.collectPaths(storage);
    const indexMap = new IndexMap();

    // add all resources we found in live storage
    resourcePaths.forEach((resourcePath) => {
      const { ext } = splitExtension(resourcePath);
      const webPath = toWebPath(resourcePath);

      if (containsPath(index, webPath)) {
        if (shouldIndex(includeOther, ext) && !excludes.includes(resourcePath)) {
          indexMap.addLive(webPath);
        }
      }
    });

    // add all resources we found in all index targets
    await processQueue([...index.indices], async (config) => {
      const data = await new IndexContents(config).load(contentBusId, storage, log) || [];
      for (const row of data) {
        if (pathList.contains(row.path)) {
          indexMap.addIndexed(config.name, row);
        }
      }
    });
    return indexMap;
  }

  /**
   * Reindex a single record.
   *
   * @param {BulkContext} bulkContext bulk context
   * @param {string} webPath webpath
   * @param {import('./IndexMap.js').IndexRecord} indexRecord index record
   */
  async reindexRecord(bulkContext, webPath, indexRecord) {
    const { context, info } = this;
    const { log } = context;
    const { headers, index, messages } = bulkContext;

    const fetchURL = info.getLiveUrl(webPath);
    const page = await fetchPage(context, fetchURL, headers /* TODO: retry params */);
    if (page.error) {
      log.warn(`Unable to index ${webPath}: ${page.error}`);
      return;
    }
    if (page.status === 404 || page.status === 301) {
      page.gone = true;
    }
    index.indices
      .filter(({ name }) => this.includeIndex(name))
      .filter((config) => contains(config, webPath))
      .forEach((config) => {
        const type = getIndexType(config, bulkContext.type);
        const { record, noIndex } = indexPageInIndex(webPath, config, page, log);
        if (noIndex) {
          messages.appendDeleted(config.name, webPath, type, log);
        }
        if (record) {
          record.path = webPath;
          const hashed = IndexMap.hash(record);
          if (hashed !== indexRecord.indexHash[config.name]) {
            messages.appendChanged(config.name, type, record, log);
          } else {
            log.debug(`record of ${webPath} already in index ${config.name}`);
          }
        }
      });
  }

  /**
   * Process a single record that should be indexed.
   *
   * @param {BulkContext} bulkContext bulk context
   * @param {string} webPath webpath
   * @param {import('./IndexMap.js').IndexRecord} indexRecord index record
   */
  async processRecord(bulkContext, webPath, indexRecord) {
    const { context: { log } } = this;
    const { messages } = bulkContext;

    if (indexRecord.live) {
      log.info(`Reindexing: ${webPath}`);
      await this.reindexRecord(bulkContext, webPath, indexRecord);
      return;
    }
    log.info(`Reindexing: ${webPath} (deleted)`);
    Object.keys(indexRecord.indexHash).forEach((name) => {
      messages.appendDeleted(name, webPath, bulkContext.type, log);
    });
  }

  /**
   * Runs the reindex job.
   * @return {Promise<void>}
   */
  async run() {
    const { context, info } = this;

    // preparing
    await this.initialize(this.state.data);
    if (this.isFullReindex) {
      await installSimpleSitemap(context, info, true);
    }
    const bulkContext = await this.prepare();

    // collecting
    await this.setPhase('collecting');
    const indexData = await this.getIndexData(bulkContext);
    await this.trackProgress({
      total: indexData.size,
    });

    // indexing
    await this.setPhase('indexing');
    await processQueue(indexData.entries(), async ([webPath, indexRecord]) => {
      if (await this.checkStopped() || webPath.startsWith('/.helix/')) {
        return;
      }
      await this.processRecord(bulkContext, webPath, indexRecord);

      this.state.progress.processed += 1;
      await this.writeStateLazy();
    }, JOB_CONCURRENCY);

    // sending
    const { messages } = bulkContext;
    await messages.send(context);

    await this.setPhase('completed');
  }
}
