/*
 * Copyright 2025 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
import { Response } from '@adobe/fetch';
import { cleanupHeaderValue } from '@adobe/helix-shared-utils';
import { fetchPage } from './fetch-page.js';
import { indexPage } from './index-page.js';
import {
  containsPath, fetchExtendedIndex, getFetchHeaders, getIndexTargets,
} from './utils.js';

/**
 * Retrieves the index status.
 *
 * @param {import('../support/AdminContext').AdminContext} context context
 * @param {import('../support/RequestInfo').RequestInfo} info request info
 * @returns {Promise<Response>} response
 */
export default async function status(context, info) {
  const { log } = context;
  const {
    org, site, webPath, resourcePath,
  } = info;

  let index;
  try {
    index = await fetchExtendedIndex(context, info);
  } catch (e) {
    log.warn(`error fetching index: ${e.message}`);
  }
  if (!index) {
    return new Response('', {
      status: 404,
      headers: {
        'x-error': `no index configuration could be loaded for document ${org}/${site}${resourcePath}`,
      },
    });
  }

  // optization: if resource is not contained in any definition, do not fetch HTML
  if (webPath.startsWith('/.helix/') || !containsPath(index, webPath)) {
    const results = index.indices.map((config) => ({
      name: config.name,
      message: 'requested path does not match index configuration',
    }));
    return new Response(JSON.stringify({ webPath, resourcePath, results }), {
      status: 200,
      headers: {
        'content-type': 'application/json',
      },
    });
  }

  const excludes = getIndexTargets(index);
  if (excludes.includes(resourcePath)) {
    return new Response('', {
      status: 204,
      headers: {
        'x-error': cleanupHeaderValue('index targets can not be indexed'),
      },
    });
  }

  const autoGenerated = index['auto-generated'] === true;
  const fetchURL = info.getLiveUrl();
  const headers = await getFetchHeaders(context, info);

  const page = await fetchPage(context, fetchURL, headers);
  if (page.error) {
    return new Response('', {
      status: page.status,
      headers: {
        'x-error': cleanupHeaderValue(page.error),
      },
    });
  }
  if (page.status === 301 || page.status === 404) {
    page.gone = true;
  }
  const results = index.indices.map((config) => {
    const result = indexPage(webPath, config, page, autoGenerated, log);
    return { name: config.name, result };
  });
  return new Response(JSON.stringify({ webPath, resourcePath, results }), {
    status: 200,
    headers: {
      'content-type': 'application/json',
    },
  });
}
