name: Build
on: [push]

env:
  CI_BUILD_NUM: ${{ github.run_id }}
  CI_BRANCH: ${{ github.ref_name }}

permissions:
  id-token: write
  contents: write  # semantic-release-dry verifies the write permissions
  issues: read # needed by semantic-release
  pull-requests: write # needed by semantic-release

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js 20.x
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
      - name: setup .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - run: npm install
      - run: npm run lint
      - run: npm test
      - run: npm run docs:lint
      - uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  test-deploy:
    name: Test Deploy
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    needs: test
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js 20.x
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
      - name: setup .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - run: npm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::118435662149:role/helix-gh-deploy-config-service
      - name: Fetch AWS Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          parse-json-secrets: true
          secret-ids: |
            ,/helix/github-action-secrets

      - name: Branch Deployment
        run: npm run deploy-ci
        env:
          HLX_TEST_HEADERS: ${{ secrets.HLX_TEST_HEADERS }}
      - name: Post-Deployment Integration Test
        run: npm run test-postdeploy
        env:
          HLX_TEST_HEADERS: ${{ secrets.HLX_TEST_HEADERS }}

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: test
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js 20.x
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
      - name: setup .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - run: npm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::118435662149:role/helix-gh-deploy-config-service
      - name: Fetch AWS Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          parse-json-secrets: true
          secret-ids: |
            ,/helix/github-action-secrets
      - name: Semantic Release
        run: npm run semantic-release
        env:
          HLX_TEST_HEADERS: ${{ secrets.HLX_TEST_HEADERS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # publish api docs to https://www.hlx.live/docs/api.html
      - name: Publish docs (check out)
        if: github.ref == 'refs/heads/main'
        uses: actions/checkout@v6
        with:
          repository: adobe/helix-website
          ssh-key: ${{ secrets.WEBSITE_DEPLOY_KEY }}
          path: website
      - name: Publish docs (deploy)
        if: github.ref == 'refs/heads/main'
        run: |
          cd $GITHUB_WORKSPACE/website
          cp $GITHUB_WORKSPACE/docs/api.html docs/api.html
          if [[ -n $(git status --porcelain) ]]
          then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add docs/api.html
            git commit -m "chore(docs): update API service docs [skip ci]"
            git push
          fi
